### ISSUE TITLE
New Instance: pin.whateveritworks.org

### ISSUE THREAD

**Issue by xbdmHQ** [Ahwxorg/Binternet#11]
Clearnet: https://pin.whateveritworks.org/
Country: Germany

**Comment by xbdmHQ** [comment]
@Ahwxorg

**Comment by Ahwxorg** [comment]
I'm sorry. New laptop wasn't logged in shenanigens... Adding it right now.

**Comment by Ahwxorg** [comment]
Please remove CloudFlare from your instance.

https://stallman.org/cloudflare.html

>  It acts as a man-in-the-middle in encrypted (HTTPS) communication between the visitor and the site: Cloudflare knows what page the visitor is looking at and sees any other communication as well.

**Comment by xbdmHQ** [comment]
Fixed!

**Comment by Ahwxorg** [comment]
<img width="436" alt="image" src="https://github.com/Ahwxorg/Binternet/assets/87855602/ec50fd8e-2240-455e-a73f-6aa4a8e84a7b">
