### ISSUE TITLE
 New Instance: e.opnxng.com

### ISSUE THREAD

**Issue by extremelyonline** [Ahwxorg/Binternet#12]
e.opnxng.com
Country: Singapore

I'm using Cloudflare but only as DNS (grey cloud instead of oracle cloud). Hope this is ok.

Moreover, may I ask  if there is a way to disable the image proxy feature?

**Comment by Ahwxorg** [comment]
There is currently no way to disable the image proxy feature. This is one of the main "selling points" for Binternet.

**Comment by Ahwxorg** [comment]
Yeah as long as you do not use CloudFlare proxying, it's good. CloudFlare proxying decrypts SSL traffic, identifies users, etc. Their DNS does not, since it cannot.

**Comment by Ahwxorg** [comment]
It looks like you've changed the source code tho(?)

**Comment by Ahwxorg** [comment]
Alright. That's fine.
