### ISSUE TITLE
Dockerfile doesn't work

### ISSUE THREAD

**Issue by extremelyonline** [Ahwxorg/Binternet#19]
Hello, I was trying to build a Docker image (for an ARM machine), and found out that the latest Dockerfile doesn't build a working image (for both ARM and AMD machines). The error is `docker/entrypoint.sh: not found.`

Yet, the container on the repo works.

**Comment by Ahwxorg** [comment]
I am not really good with Docker, I know @kubo6472 did this for LibreY. They might be able to help?

**Comment by kubo6472** [comment]
@Ahwxorg @extremelyonline you are missing [this file](https://github.com/Ahwxorg/LibreY/blob/main/docker/entrypoint.sh).

**Comment by codedipper** [comment]
WHY do you make things so complicated? Dockerfiles are literally shell scripts on AIDS. #21

**Comment by kubo6472** [comment]
> WHY do you make things so complicated? Dockerfiles are literally shell scripts on AIDS. #21

Note, I did not create the dockerfile, only the GHCR build script :)

**Comment by codedipper** [comment]
> > WHY do you make things so complicated? Dockerfiles are literally shell scripts on AIDS. #21
> 
> Note, I did not create the dockerfile, only the GHCR build script :)

I know, but liv *did* blindly copy and paste the Docker from LibreX. :)

**Comment by codedipper** [comment]
@extremelyonline please test the new Docker image, you can build with: 
```sh
[doas/sudo] docker buildx build --no-cache --platform linux/[arm64v8] --tag ahwxorg/binternet:latest .
```
@Ahwxorg please add the new information to the wiki.
