### ISSUE TITLE
Searching for pictures only displays the first page of Pinterest results (22 ± 3 posts)

### ISSUE THREAD

**Issue by BeanieBarrow** [Ahwxorg/Binternet#2]
## Current output

Only around 20-25 pictures are shown when searching for any query. This happens on both instances (ahwx and revvy). Using the original site, the pictures appear gradually (~20 load, then if the user scrolls, more posts appear).

## Steps to reproduce

1. Use any instance (for example pinternet.ahwx.org),
2. Search for any query with moderate interest.

## Expected output

Similar behavior to the original site.

**Comment by stemy2** [comment]
> Hey! Thanks for showing interest in my project! :)
> 
> It seems to be an issue/limitation with Pinterest's API. I cannot get any results showing more pictures.

Does it means that the problem is unsolvable ?

**Comment by Ahwxorg** [comment]
Seems like it. I might recode it later but depression hits like a bus.

**Comment by Ahwxorg** [comment]
Honestly we could make web scraping a thing but I feel like we need to emulate a browser then, since Pinterest depends on loading when the bottom of a page is hit.
