### ISSUE TITLE
Any plan for backlinks? 

### ISSUE THREAD

**Issue by 825i** [Ahwxorg/Binternet#27]
So far it's flawless with the one caveat that if I am searching for eg. Terrarium plants. Often many of the hits are links to guides for the best Terrarium plants etc.

In short, 
It would be nice to be able to follow the source of the image back to where it came from. Then the app would be both privacy respecting and author/copyright respecting.

Thanks

**Comment by Ahwxorg** [comment]
This is not planned at the moment.
