### ISSUE TITLE
New Instance!

### ISSUE THREAD

**Issue by blade10101** [Ahwxorg/Binternet#35]
I have  a new instance up and running

https://binternet.darkness.services
No Cloudflare
US Based
10 Gbit

**Comment by Ahwxorg** [comment]
Merged on commit [5a84d04ba1f831457d92865e36947a30a47412a2](https://github.com/Ahwxorg/Binternet/commit/5a84d04ba1f831457d92865e36947a30a47412a2)

**Comment by blade10101** [comment]
https://binternet.darkness.services/
No Cloudflare
US Based
10 Gbit

http://binternet.darknessrdor43qkl2ngwitj72zdavfz2cead4t5ed72bybgauww5lyd.onion/
