### ISSUE TITLE
docker-compose issues

### ISSUE THREAD

**Issue by Ftonans** [Ahwxorg/Binternet#38]
`git clone https://github.com/Ahwxorg/Binternet/ && cd Binternet`

`docker compose up -d`

`docker compose logs`
```
binternet  | [21-Jul-2024 09:50:31] ERROR: failed to open error_log (/var/log/php83/error.log): No such file or directory (2)
binternet  | [21-Jul-2024 09:50:31] ERROR: failed to post process the configuration
binternet  | [21-Jul-2024 09:50:31] ERROR: FPM initialization failed
```

I think we can use [this](https://github.com/TrafeX/docker-php-nginx) as a base for a secure and reliable Docker image for Binternet

**Comment by Ahwxorg** [comment]
Issue has been fixed in [commit 0d1e0638dd118a0af374182f6874901fa54c7c11](https://github.com/Ahwxorg/Binternet/commit/0d1e0638dd118a0af374182f6874901fa54c7c11).
