### ISSUE TITLE
New instance binternet.privacyredirect.com

### ISSUE THREAD

**Issue by Conceded2** [Ahwxorg/Binternet#39]
URL: https://binternet.privacyredirect.com
Hosted in Finland
No Tor or I2P

**Comment by Ahwxorg** [comment]
Added in [commit 5f3b13344d2bc69ea3135bf8ac8795657c3e40c1](https://github.com/Ahwxorg/Binternet/commit/5f3b13344d2bc69ea3135bf8ac8795657c3e40c1).
