### ISSUE TITLE
New Instance - binternet.lunar.icu

### ISSUE THREAD

**Issue by MaximilianGT500** [Ahwxorg/Binternet#40]
URL: https://binternet.lunar.icu
Hosted in Germany
No Tor or I2P

**Comment by Ahwxorg** [comment]
Done in [commit a9e0d2c713b5ea2b3c1573a7324ced9646af153c](https://github.com/Ahwxorg/Binternet/commit/a9e0d2c713b5ea2b3c1573a7324ced9646af153c)
