### ISSUE TITLE
Found an instance on i2p

### ISSUE THREAD

**Issue by WatchOfTime** [Ahwxorg/Binternet#41]
http://verne3vnw4i3qffozcjygtnv4uedwedtevxe7aoht7fngduuwcpa.b32.i2p 
I don't know if there's a clearnet or tor url.

**Comment by Ahwxorg** [comment]
If the instance is not requested by someone, I will not include it. This is due to me not wanting to interfere in people hosting their services only for them or their friends - or on data plans.

**Comment by WatchOfTime** [comment]
Understandable, have a nice day.

**Comment by codedipper** [comment]
Pretty sure those are the ~vern guys, their instance [was](5665210dd4b3ad079549719a6da40859a034db9f) listed here but later [removed](7e05853a52a4e71658d3886162e6e45639106bb4) as they had a big outage.
