### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [Ahwxorg/Binternet#9]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `binternet.esmailelbob.xyz` / `binternet.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.

*See the commit here: https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by Ahwxorg** [comment]
I am so sorry. I did not see this in their documentation. I wil contact the host and will (maybe not) take action based on what I get back from them.

**Comment by Ahwxorg** [comment]
@EsmailELBoBDev2, I do not condone homo/transphobia and I have removed your instance from the list. Of course, you can keep hosting it yourself if you'd like. You're just not going to be in the official instances list.

See commit [372c3b5](https://github.com/Ahwxorg/Binternet/commit/372c3b509f77e8c754448d4683025d87ba31098f)
